### ISSUE TITLE
Command not found triggered by too many strings

### ISSUE THREAD

**Issue by valknight** [Valerokai/gssp_experiments#10]
**Describe the bug**
Command not found, even when multiple question marks are used, or a single one.

**To Reproduce**
1. Type ???
2. Bot says "command not found"

**Expected behavior**
Nothing to happen.

**Screenshots**
https://i.imgur.com/ZWZQMMr.png

**Only occurs on some discord clients?**
Occurs on all.

**Comment by TBTerra** [comment]
looks like it needs to check if the bot prefix is followed by another bot prefix, and if it is ignore it.

that would stop it thinking any string of ? was a command

**Comment by valknight** [comment]
Fixed in 8819f5b1ef1fed3a8241a6202e8994ecc1cccee4
